excluded:
    - Pods
    - GoodMorningTests
    - GoodMorningUITests
    - GoodMorning/AppDelegate.swift
    - GoodMorning/SceneDelegate.swift
opt_in_rules:
    - force_unwrapping
    - function_body_length
    - line_length
    - weak_delegate
    - trailing_newline
disabled_rules:
    - unused_closure_parameter
    - closure_parameter_position
function_body_length:
    error: 30
line_length:
    error: 100
