# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodMorning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'SnapKit'

  # Pods for GoodMorning

  target 'GoodMorningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoodMorningUITests' do
    # Pods for testing
  end

end
